---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: justin-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
      - source: scripts/install-common-flatpaks.sh
        destination: /usr/local/bin/install-common-flatpaks.sh
      - source: scripts/flatpak-auto-update.sh
        destination: /usr/local/bin/flatpak-auto-update.sh

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.gnome.Loupe
      - scope: user # Also add Flathub user repo, but no user packages

  # Import all the modular pieces
  - from-file: common-repos.yml
  - from-file: common-packages.yml
  - from-file: common-packages-dev.yml
  - from-file: common-systemd.yml
  - from-file: vpn-fix.yml
  - from-file: files.yml
  - from-file: common-flatpaks.yml
  - from-file: zsh-user-shell.yml

  # Configure shells and zsh (BEFORE changing /bin/sh)
  - type: script
    scripts:
      - set-default-shell-zsh.sh
      - setup-oh-my-zsh.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  # Change /bin/sh to dash (MUST BE LAST - after all package operations)
  - type: script
    scripts:
      - set-dash-as-sh.sh
